import { useState } from 'react';
import { Card, CardContent } from '@/components/ui/Card';

export default function FAQPage() {
  const [openItems, setOpenItems] = useState<number[]>([]);

  const toggleItem = (index: number) => {
    setOpenItems(prev =>
      prev.includes(index)
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  const faqCategories = [
    {
      title: 'GST Basics',
      questions: [
        {
          q: 'What is GST and how does it work?',
          a: 'GST (Goods and Services Tax) is a comprehensive indirect tax levied on the supply of goods and services in India. It has replaced multiple indirect taxes and is levied at every stage of the supply chain.'
        },
        {
          q: 'What is the difference between CGST, SGST, and IGST?',
          a: 'CGST (Central GST) and SGST (State GST) are levied on intra-state supply (same state) and are split equally. IGST (Integrated GST) is levied on inter-state supply (different states) and goes to the central government.'
        },
        {
          q: 'What are the current GST rates in India?',
          a: 'The current GST rates are 0%, 5%, 12%, 18%, and 28%. Different goods and services fall under different tax slabs as specified by the GST council.'
        }
      ]
    },
    {
      title: 'Invoice Creation',
      questions: [
        {
          q: 'What information is required in a GST invoice?',
          a: 'A GST invoice must include: business name and GSTIN, customer name and address, invoice number and date, place of supply, HSN codes (for goods), item details with tax rates, and tax breakdown (CGST/SGST/IGST).'
        },
        {
          q: 'How is place of supply determined?',
          a: 'Place of supply is typically where the goods are delivered or services are rendered. For intra-state supply, CGST+SGST applies; for inter-state supply, IGST applies.'
        },
        {
          q: 'Can I edit an invoice once created?',
          a: 'Yes, you can edit invoice details before generating the PDF. However, once a PDF is generated and shared, it\'s recommended to issue a credit note for any corrections rather than modifying the original invoice.'
        }
      ]
    },
    {
      title: 'Technical Support',
      questions: [
        {
          q: 'Is my data secure on this platform?',
          a: 'Yes, all your invoice data is processed locally in your browser and is not stored on our servers unless you explicitly choose to save invoices by creating an account.'
        },
        {
          q: 'Can I use this tool without registration?',
          a: 'Yes, you can create and download invoices without registration. Registration is only required if you want to save your invoices for future reference.'
        },
        {
          q: 'What browsers are supported?',
          a: 'Our GST Bill Maker works on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version for the best experience.'
        }
      ]
    },
    {
      title: 'Business & Legal',
      questions: [
        {
          q: 'Are the generated invoices legally valid?',
          a: 'Yes, the invoices generated by our tool follow the format specified by GST regulations in India. However, ensure that all information is accurate and you maintain proper records as required by law.'
        },
        {
          q: 'Do I need to register for GST?',
          a: 'GST registration is mandatory for businesses with annual turnover above ₹20 lakhs (₹10 lakhs for special category states). It\'s recommended to consult with a tax professional for specific advice.'
        },
        {
          q: 'How long should I maintain invoice records?',
          a: 'As per GST regulations, you should maintain invoice records for at least 6 years from the due date of filing the annual return for the year in which the invoice was issued.'
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-primary-600 text-white py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold mb-4">Frequently Asked Questions</h1>
            <p className="text-xl text-primary-100">
              Get answers to common questions about GST billing and our invoice generator
            </p>
          </div>
        </div>
      </div>

      {/* FAQ Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {faqCategories.map((category, categoryIndex) => (
          <div key={categoryIndex} className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">
              {category.title}
            </h2>
            <div className="space-y-4">
              {category.questions.map((item, itemIndex) => {
                const globalIndex = categoryIndex * 100 + itemIndex;
                const isOpen = openItems.includes(globalIndex);

                return (
                  <Card key={globalIndex} className="overflow-hidden">
                    <CardContent className="p-0">
                      <button
                        className="w-full px-6 py-4 text-left flex justify-between items-center hover:bg-gray-50 transition-colors"
                        onClick={() => toggleItem(globalIndex)}
                      >
                        <span className="font-medium text-gray-900">{item.q}</span>
                        <svg
                          className={`w-5 h-5 text-gray-500 transition-transform ${
                            isOpen ? 'transform rotate-180' : ''
                          }`}
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                      {isOpen && (
                        <div className="px-6 py-4 border-t border-gray-200">
                          <p className="text-gray-600">{item.a}</p>
                        </div>
                      )}
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        ))}

        {/* Additional Help */}
        <div className="mt-12 bg-primary-50 rounded-lg p-8 text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">
            Still have questions?
          </h2>
          <p className="text-gray-600 mb-6">
            Can't find the answer you're looking for? Our support team is here to help you.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="/contact"
              className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700"
            >
              Contact Support
            </a>
            <a
              href="https://wa.me/919876543210?text=Hi%20I%20need%20help%20with%20GST%20Bill%20Maker"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center px-6 py-3 border border-gray-300 text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
            >
              WhatsApp Support
            </a>
          </div>
        </div>

        {/* Quick Links */}
        <div className="mt-12">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Quick Links</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <a href="/" className="text-primary-600 hover:text-primary-700">
              ← Back to GST Bill Maker
            </a>
            <a href="/templates" className="text-primary-600 hover:text-primary-700">
              View Invoice Templates →
            </a>
            <a href="/about" className="text-primary-600 hover:text-primary-700">
              About Us →
            </a>
            <a href="/contact" className="text-primary-600 hover:text-primary-700">
              Contact Us →
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}